### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by bradintheusa** [mve/vue-component-npm-example#1]
Hi

This is super helpful and let me progress a long way to making my own packages. I can get my app to run in dev fine but the build give this error

```
src/App.vue:3:36 - error TS7016: Could not find a declaration file for module 'vue-component-npm-example'. 'D:/GitHub/pubic/vue3Components/example-app/node_modules/vue-component-npm-example/dist/vue-component-npm-example.ssr.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-component-npm-example` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-component-npm-example';`

3 import VueComponentNpmExample from "vue-component-npm-example";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/App.vue:3

The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build" terminated with exit code: 1.

```

I'd like to learn how to fix this on the package side so my packages wont have this error.

**Comment by mve** [comment]
Hey there,

I believe this is because you are using this in a TypeScript project and this example just uses JavaScript.

I found this question on StackOverflow that should be able to answer this question for you.
https://stackoverflow.com/questions/49258849/could-not-find-a-declaration-file-for-module-vue-xxx

**Comment by bradintheusa** [comment]
Thanks
